### ISSUE TITLE
Proofman

### ISSUE THREAD

**Issue by xavi-pinsach** [0xPolygonHermez/pil2-proofman-js#2]

**Comment by xavi-pinsach** [comment]
# TODO List (add all tasks pending)

- [X] Generate a STARK from PIL2 with one subproof and one air
- [X] Make pil2 stark tests (simple+fibonacci) work in this repo
- [X] Integrate PIL verify as a "debug" flag
- [X] Integrate basic verifiers circom circuits in tests
- [·] *WIP* Write recursive1, recursive2 and recursivef circuits
- [] Generate a STARK from PIL2 with one subproof and multiple airs
- [] Generate a STARK from PIL2 with multiple subproofs and multiple airs

**Comment by xavi-pinsach** [comment]
✅ **Done**
* Create and Verify a STARK proof with **1 subproof : 1 AIR** using publics from hints
* Create a STARK proof(s) with **N subproofs : M AIRs** using publics from hints. NOTE: challenges synchronised from a binary tree (aggregated) root hash.

🏗️ **In progress**
* Verify a STARK proof(s) with **N subproofs : M AIRs** using publics from hints (expecting to be done wednesday morning)
* Generate documentation for currently developed code

🔜 **Next**
* Aggregate STARK AIRs

👀 **In review**
* Executors' communication architecture

📋**Backlog**
* Review snarkjs PR 434 "Add Browser ES module build"

**Comment by xavi-pinsach** [comment]
✅ Done
New Executor's communication architecture with threading
PIL2-Stark refactor to calculate expressions independently
🏗️ In progress
Integrating recursive aggregation circuits
New memory API management:
Done in Javascript, pending to integrate this week
WIP in RUST (almost done the API management, next step is a prototype to mock the communication architecture with threadings using this API).
Generate documentation for currently developed code
🔜 Next
Create and Verify a STARK proof with N subproofs : M AIRs aggregating AIRs
📋 Backlog
Explore GKR to assess its potential impact on our prover (and associated changes)
